server:
  build: .
  # image: dockerfile/nodejs-bower-gulp-runtime
  ports:
   - "9050:9050"
  links:
   - "rethinkdb"
  environment:
    NODE_ENV: production
    PORT: 9050
rethinkdb:
  image: dockerfile/rethinkdb
  ports:
   - "9051:8080"
   - "28015:28015"
   - "29015:29015"